
// basket reducer types
export const ADD_ITEM_TO_BASKET = "ADD_ITEM_TO_BASKET"
export const DELETE_ITEM_FROM_BASKET = "DELETE_ITEM_FROM_BASKET"
export const SET_BASKET_LOADING = "SET_BASKET_LOADING"
export const SET_BASKET_ERROR = "SET_BASKET_ERROR"


// products reducer types
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT"
export const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING"
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR"