

export const ADD_ITEM_TO_BASKET = "ADD_ITEM_TO_BASKET"
export const DELETE_ITEM_FROM_BASKET = "DELETE_ITEM_FROM_BASKET"
export const SET_BASKET_LOADING = "SET_BASKET_LOADING"
export const SET_BASKET_ERROR = "SET_BASKET_ERROR"